### ISSUE TITLE
Parse Rust doc comment markdown to extract arguments and return value description.

### ISSUE THREAD

**Issue by zduny** [eigerco/uniffi-rs#5]
- [ ] Doc comment parsing
- [ ] Check if templates behave correctly

**Comment by zduny** [comment]
Rust doc comments use [Markdown](https://en.wikipedia.org/wiki/Markdown) to provide rich formatting (and linking) for their content.

The goal of this task is to parse this Markdown to extract functions argument descriptions and return value description.

We'll use following convention for doc comments*:
```rust
/// This is the function description
///
/// # Arguments
///
/// - `argument` - this is argument description.
///
/// # Returns
///
/// This is return value description
pub fn get_option(&self, option: Rs2Option) -> Option<f32>;
```

*note this convention is actually **discouraged** in Rust, we're using it for our bindings, as it's a convention that is similar to that used in foreign language doc comments, see KDoc for example here:

```kotlin
/**
* Add two numbers together
*
* @param value_1 is first input
* @param value_2 is second input
*
* @return this function return [value_1] + [value_2]
*/
fun add(value_1: Int, value_2: Int): Int{
    return value_1 + value_2
}
```

**Comment by zduny** [comment]
So, basically create a function you could call to parse `&str` with description Markdown that will return `Function` with filled fields and call it here:

https://github.com/eigerco/uniffi-rs/blob/8b43429f3a4170f02aa796651620a69ed0d4650c/uniffi_docs/src/lib.rs#L106-L116

If Markdown can't be parsed then just treat it all as function description and leave other fields empty (and maybe show a warning?).

**Comment by eloylp** [comment]
Hi @zduny we have an initial version for review. Let me know your thoughts in comments there.

* https://github.com/eigerco/uniffi-rs/pull/6

**Comment by eloylp** [comment]
I think #6 fully closes this, if not, just reopen.
